MVCManukauTech/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MVCManukauTech.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCManukauTech/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCManukauTech.Models.DB;
using Microsoft.AspNetCore.Authorization;

namespace MVCManukauTech.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly XSpyContext _context;

        public ProductsController(XSpyContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var xSpyContext = _context.Product.Include(p => p.Category);
            return View(await xSpyContext.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,CategoryId,Name,ImageFileName,UnitCost,Description,IsDownload,DownloadFileName")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", product.CategoryId);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", product.CategoryId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ProductId,CategoryId,Name,ImageFileName,UnitCost,Description,IsDownload,DownloadFileName")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", product.CategoryId);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(string id)
        {
            return _context.Product.Any(e => e.ProductId == id);
        }
    }
}

MVCManukauTech/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCManukauTech.Models.DB;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;

namespace MVCManukauTech.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReportsController : Controller
    {
        private readonly XSpyContext _context;
        public ReportsController(XSpyContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            string sql = @"SELECT o.OrderId, o.Username, o.DateOfOrder, o.TransactionId, o.GrandTotal 
            FROM [Order] o";
            var ordersSummary = _context.ReportsViewModel.FromSqlRaw(sql).ToList();
            return View(ordersSummary);
        }
    }
}

MVCManukauTech/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCManukauTech.Models.DB;
using Microsoft.AspNetCore.Http;

namespace MVCManukauTech.Controllers
{
    public class StoreController : Controller
    {
        private readonly XSpyContext _context;

        public StoreController(XSpyContext context)
        {
            _context = context;
        }

        //Eddril - added nulls to match ViewModel
        // GET: Store?CategoryName=Travel
        public IActionResult Index()
        {
            //140903 JPC add CategoryName to SELECT list of fields
            string SQL = @"SELECT DISTINCT p.ProductId, p.CategoryId AS CategoryId, p.Name, p.ImageFileName, p.UnitCost, 
            p.Description, CategoryName, '' AS Username, NULL AS ExpiryDate, NULL AS MemberDiscount 
            FROM Product p 
            INNER JOIN Category c ON p.CategoryId = c.CategoryId";

            string categoryName = Request.Query["CategoryName"];

            if (categoryName != null)
            {
                //140903 JPC security check - if ProductId is dodgy then return bad request and log the fact 
                //  of a possible hacker attack.  Excessive length or containing possible control characters
                //  are cause for concern!  TODO move this into a separate reusable code method with more sophistication.
                if (categoryName.Length > 20 || categoryName.IndexOf("'") > -1 || categoryName.IndexOf("#") > -1)
                {
                    //TODO Code to log this event and send alert email to admin
                    return BadRequest(); // Http status code 400
                }

                //140903 JPC  Passed the above test so extend SQL
                //150807 JPC Security improvement @p0
                SQL += " WHERE CategoryName = @p0";
                //SQL += " WHERE CategoryName = '{0}'";
                //SQL = String.Format(SQL, CategoryName);
                //Send extra info to the view that this is the selected CategoryName
                ViewBag.CategoryName = categoryName;
            }

            //150807 JPC Security improvement implementation of @p0
            var products = _context.StoreViewModel.FromSqlRaw(SQL, categoryName).ToList();

            //Eddril - Get Membership details and link to products
            var subscribeDetail = _context.SubscribeDetail
                    .Include(a => a.Subscribe)
                    .OrderByDescending(t => t.Subscribe.ExpiryDate)
                    .FirstOrDefault(a => a.UserName == User.Identity.Name);

            //Eddril - check if user is a member or subscribed to show member discount
            if (subscribeDetail != null)
            {
                //if (subscribeDetail.Subscribe.ExpiryDate > DateTime.Now)
                var memberships = _context.Membership.FirstOrDefault(a => a.MembershipId == subscribeDetail.MembershipId);

                if (memberships != null)
                {
                    products.ForEach(product =>
                    {
                        product.UserName = subscribeDetail.UserName;
                        product.ExpiryDate = subscribeDetail.Subscribe.ExpiryDate;
                        product.MemberDiscount = memberships.MemberDiscount;
                    });
                }
            }

            return View(products);
        }

        // GET: Store/Details?ProductId=1MORE4ME
        public IActionResult Details(string ProductId)
        {
            if (ProductId == null)
            {
                return BadRequest(); // Http status code 400
            }
            //140903 JPC security check - if ProductId is dodgy then return bad request and log the fact 
            //  of a possible hacker attack.  Excessive length or containing possible control characters
            //  are cause for concern!  TODO move this into a separate reusable code method with more sophistication.
            if (ProductId.Length > 20 || ProductId.IndexOf("'") > -1 || ProductId.IndexOf("#") > -1)
            {
                //TODO Code to log this event and send alert email to admin
                return BadRequest(); // Http status code 400
            }

            //150807 JPC Security improvement implementation of @p0
            //20180312 JPC change to query based on class CatalogViewModel
            //  Change above code to give all of the description rather than summarising with the first 100 characters
            string SQL = @"SELECT p.ProductId, p.CategoryId AS CategoryId, p.Name, p.ImageFileName, p.UnitCost, 
            p.Description, CategoryName, '' AS Username, NULL AS ExpiryDate, NULL AS MemberDiscount 
            FROM Product p 
            INNER JOIN Category c ON p.CategoryId = c.CategoryId 
            WHERE ProductId = @p0";

            //140904 JPC case of one product to look at the details.
            //  SQL gives some kind of collection where we need to clean that up with ToList() then take element [0]
            //150807 JPC Security improvement implementation of @p0 substitute ProductId
            var product = _context.StoreViewModel.FromSqlRaw(SQL, ProductId).ToList()[0];

            //Eddril - Get Membership details and link to products
            var subscribeDetail = _context.SubscribeDetail
                    .Include(a => a.Subscribe)
                    .OrderByDescending(t => t.Subscribe.ExpiryDate)
                    .FirstOrDefault(a => a.UserName == User.Identity.Name);

            //Eddril - check if user is a member or subscribed to show member discount
            if (subscribeDetail != null)
            {
                //if (subscribeDetail.Subscribe.ExpiryDate > DateTime.Now)
                var memberships = _context.Membership.FirstOrDefault(a => a.MembershipId == subscribeDetail.MembershipId);

                if (memberships != null)
                {
                    product.UserName = subscribeDetail.UserName;
                    product.ExpiryDate = subscribeDetail.Subscribe.ExpiryDate;
                    product.MemberDiscount = memberships.MemberDiscount;
                }
            }

            if (product == null)
            {
                return NotFound(); //Http status code 404
            }

            return View(product);
        }

    }
}

MVCManukauTech/Views/Shared/_AdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using MVCManukauTech.Areas.Identity.Data;
@inject SignInManager<MVCManukauTechUser> SignInManager
@inject UserManager<MVCManukauTechUser> UserManager


@if (User.Identity.IsAuthenticated)
{
    if (User.IsInRole("Admin"))
    {
        <section class="p-3 mb-2 adminPanel">
            <div class="row">
                <div class="col-md-6">
                    <a asp-area="" asp-controller="Products" asp-action="Index">Products</a> | 
                    <a asp-area="" asp-controller="Memberships" asp-action="Index">Memberships</a> | 
                    <a asp-area="" asp-controller="Reports" asp-action="Index">Reports</a>
                </div>
                <div class="col-md-6 text-right welcome-admin">
                    Welcome, Admin
                </div>
            </div>
        </section>
    }
}

MVCManukauTech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Glorious End Music</title>

    <!-- 2019-03-19 JPC Bootstrap CDN links from W3Schools
        https://www.w3schools.com/bootstrap4/bootstrap_get_started.asp  -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/site.js"></script>
</head>
<body>
    @*Eddril - Admin Dashboard*@
    <partial name="_AdminPartial" />

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow border-bottom">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Store" asp-action="Index"><img src="~/images/logo-ge.svg" alt="Glorious End Band" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"><img src="~/images/icon-menu.svg"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <partial name="_LoginPartial" />

                    <partial name="_MenuPartial" />

                </div>
            </div>
        </nav>
    </header>

    <div id="bannerHolder"></div>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @* Eddril - Fictional message *@
            &copy; 2020 - Glorious End Band - <a asp-area="" asp-controller="About" asp-action="Index">This is a Student Project</a> (this organisation is not real).
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVCManukauTech/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using MVCManukauTech.Areas.Identity.Data;
@inject SignInManager<MVCManukauTechUser> SignInManager
@inject UserManager<MVCManukauTechUser> UserManager

<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
    </li>
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link text-danger" asp-area="" asp-controller="Subscribe" asp-action="Index">Be a Member</a>
        </li>
    }
</ul>